project_id = "zvoelshrluaotjrmxzho"

[functions.docusign-signature]
verify_jwt = false

[functions.google-oauth-callback]
verify_jwt = false

[functions.parse-booking-emails]
verify_jwt = false

[functions.smart-booking-assistant]
verify_jwt = false

[functions.setup-staff-drive]
verify_jwt = false

[functions.create-project-drive]
verify_jwt = false
 
 [functions.generate-project-charter]
 verify_jwt = false